name: "Rhyans Design Studio"
description: "Custom Jewelry"
highlighter: true
permalink: none
markdown: redcarpet
baseurl: 
github:
  # enables "edit" link
  repo: 'rhyansdesignstudio/rhyansdesignstudio.github.io'
  branch: master
prose:
  rooturl: '_posts/static'
  siteurl: 'http://rhyansdesignstudio.github.io/'
  relativeLinks: 'http:/rhyansdesignstudio.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
